### ISSUE TITLE
what is the meaning of "polar_map_reg = torch.arctan(polar_map_reg)/math.pi"？

### ISSUE THREAD

**Issue by xiaozheng666** [ShqWW/PolarRCNN#1]
code in */Models/Head/rpn_head/local_polar_head.py -> line 38:
按照我的理解，polar_map_reg第一个通道是角度，第二个通道是极径，那么只需要针对第一个通道进行反正切取值是不是就够了。

**Comment by ShqWW** [comment]
torch.arctan(·)/math.pi 没有几何意义，它的作用类似于sigmoid激活函数，作用是将输出归一化到(-0.5,0.5).。最后乘以pi 就是真实输出角度，取值范围是(-pi/2,pi/2)。当然math.pi也可以选择不加或者换成其它缩放常数。

**Comment by xiaozheng666** [comment]
多谢解答！在build_target阶段也确实看到了rho编码成了(-1/2,1/2)。
