### ISSUE TITLE
你好可否帮忙解决下这个问题：/PolarRCNN-master/ops/NMSOPS/build/temp.win-amd64-cpython-312/Release/nms_cuda/nms.obj', missing and no known rule to make it

### ISSUE THREAD

**Issue by happy-q123** [ShqWW/PolarRCNN#2]
运行python setup.py install时出现如下问题：
`Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: 'D:/python项目/PolarRCNN-master/ops/NMSOPS/nms_cuda/nms.cpp', needed by 'D:/python项目/PolarRCNN-master/ops/NMSOPS/build/temp.win-amd64-cpython-312/Release/nms_cuda/nms.obj', missing and no known rule to make it
`
困扰好几天了，求助下，谢谢

**Comment by ShqWW** [comment]
默认linux上运行，没试过在windows上编译。
有两种方法：
1.使用wsl2运行。
2.实在编译不通过的话可以跳过这步，把代码‘Models/Head/roi_head/global_polar_head.py’中nms包import和调用部分注释掉 (大概第4行和第110行左右)，只使用nms-free的模式。

**Comment by happy-q123** [comment]
> 默认linux上运行，没试过在windows上编译。 有两种方法： 1.使用wsl2运行。 2.实在编译不通过的话可以跳过这步，把代码‘Models/Head/roi_head/global_polar_head.py’中nms包import和调用部分注释掉 (大概第4行和第110行左右)，只使用nms-free的模式。

感谢您的回复。我最近装了一个linux系统，发现可以成功编译了。
